spring:
  data:
    mongodb:
      database: productdb
      host: localhost
      port: 27017
  profiles:
    active: pro
---      
spring:      
  profiles: pro
  
name: john weather


  
      
    
