spring:
  profiles:
    active: dev
      
---
  
spring:    
  profiles: production
    
  data:
    mongodb:
      uri: mongodb://192.168.99.100:32768/catalogdb  
  aop:
    proxy-target-class: true      
            
---

spring:
  profiles: dev
  
  data:
    mongodb:
      uri: mongodb://192.168.99.100:32768/testdb
      
eureka:
  client:
    enabled: false             
             
      
    
